### ISSUE TITLE
[Bug]: Inconsistent heading width

### ISSUE THREAD

**Issue by s-laugh** [DTS-STN/DECD-Design-System#234]
### What happened?

Depending on the screen size, the top part of the header is a different width than the menu part of the header.

It seems like there is a conflict when the "mobile" header takes effect.

![image](https://user-images.githubusercontent.com/22419216/163234141-ec9e65b9-a10e-44d2-94af-6d8ae9f76de4.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by AnthonyA44** [comment]
issue has been resolved and will be merged into main in a future update. Thanks for your feedback
