### ISSUE TITLE
CHANGE REQUEST: LayoutContainer shouldn't force content into a span-1 by default

### ISSUE THREAD

**Issue by s-laugh** [DTS-STN/DECD-Design-System#260]
When using the `LayoutContainer` component it forces all content by default into span-1's this requires us to always add a div overriding this.
```.js
<LayoutContainer>
  <div className="col-span-12">
    ...stuff...
  </div>
</LayoutContainer>
```
I don't believe this should be the default behavior of this component; but rather an optional one. (We also use our own grid system)

**Comment by AnthonyA44** [comment]
Will publish a new package shortly with some fixes. If there are any other concerns, feel free to open up a new issue. Thanks for your feedback
