### ISSUE TITLE
[Bug]: PIF doesn't switch for french

### ISSUE THREAD

**Issue by s-laugh** [DTS-STN/DECD-Design-System#270]
### What happened?

In the Header, the "Gov of Can" logo has both english and french and gets refereed to as the "PIF"; this should swap which language comes first for the appropriate language.
![image](https://user-images.githubusercontent.com/22419216/165995645-e971ec2b-9d43-476e-bb98-8c0ba1e8e508.png)
Gouvernement du Canada is first on a french page.
This doesn't happen with the Header component when passed an `fr` for `lang`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by AnthonyA44** [comment]
The "French logo" has been added to the header. A new package will be published with the updated changes soon.
